support/scripts: Enable generation of GRUB ISO images
This support script allows easy generation of GRUB ISO images from
Unikraft KVM images. This script is intended and designed to be
expanded to allow more formats and architectures. This script is
designed to resolve #342 as it was determined this functionality would
be better placed outside of the Unikraft build pipeline.

Signed-off-by: Aadhithya Kannan <aadhi0319@gmail.com>

diff --git a/support/scripts/mkgrubimg b/support/scripts/mkgrubimg
--- a/support/scripts/mkgrubimg
+++ b/support/scripts/mkgrubimg
@@ -54,7 +54,20 @@ shift $((OPTIND-1))
 
 # validate arguments
 if [[ -z "${OPTKERNELIMG}" || -z "$1" ]]; then
+	echo "Missing path to kernel image ('-k')" 1>&2
 	usage
+fi
+if [[ -z "${1}" ]]; then
+	echo "Missing path to output image" 1>&2
+	usage
+fi
+if [ ! -f "${OPTKERNELIMG}" ]; then
+	echo "${OPTKERNELIMG} does not exist or is not a file" 1>&2
+	exit 1
+fi
+if [ ! -z "${OPTINITRD}" -a -f "${OPTINITRD}" ]; then
+	echo "${OPTINITRD} does not exist or is not a file" 1>&2
+	exit 1
 fi
 
 # Register exit handler and create BUILDDIR
@@ -76,9 +89,9 @@ case "${OPTFORMAT}" in
 
 		if [ ! -z "${OPTINITRD}" ]; then
 			GRUB_CFG_INITRD="module /boot/${OPTINITRDNAME}"
-			cp "${OPTINITRD}" "${BUILDDIR}/boot/${OPTINITRDNAME}"
+			cp "${OPTINITRD}" "${BUILDDIR}/boot/${OPTINITRDNAME}" || exit 1
 		fi
-		cp "${OPTKERNELIMG}" "${BUILDDIR}/boot/"
+		cp "${OPTKERNELIMG}" "${BUILDDIR}/boot/" || exit 1
 
 		cat >"${BUILDDIR}/boot/grub/grub.cfg" <<EOF
 set default=0
@@ -92,7 +105,11 @@ menuentry "${OPTKERNELNAME}" {
 EOF
 
 		# build grub image
-		grub-mkrescue -o "$1" --install-modules="multiboot" --fonts="" --themes="" --locales="" "${BUILDDIR}/" &>/dev/null
+		GRUB_INSTALL_MSGS=$( grub-mkrescue -o "$1" --install-modules="multiboot" --fonts="" --themes="" --locales="" "${BUILDDIR}/" 2>&1 )
+		if [ $? != 0 ]; then
+			printf '%s\n' "$GRUB_INSTALL_MSGS" 1>&2
+			exit 1
+		fi
 		;;
 	*)
 		echo -e "\"${OPTFORMAT}\" not a supported format." 1>&2
